### ISSUE TITLE
Add "get involved" Page

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand.org#3]
Should have 3
#1 Volunteer sign up form 
#2 Slack Link
#3 GitHub roadmap link

**Comment by AlanBCole** [comment]
Okay. Where would you like the sign-up form info sent? To your e-mail or somewhere else?

**Comment by Davidezrajay** [comment]
Just that google doc sends it to a form. If you have a minute later let’s chat before you work on it.
